using Binance.Models.Enums;

namespace Binance.Requests.Margin;

/// <summary>
/// The inputs of the MarginAccountNewOrderTrade operation.
/// </summary>
public sealed record MarginAccountNewOrderTradeRequest
{
    /// <summary>
    /// Trading symbol, e.g. BNBUSDT
    /// </summary>
    public required string Symbol { get; init; }

    public required Side Side { get; init; }

    /// <summary>
    /// Order type
    /// </summary>
    public required Type1 Type { get; init; }

    public required double Quantity { get; init; }

    public required bool AutoRepayAtCancel { get; init; }

    /// <summary>
    /// UTC timestamp in ms
    /// </summary>
    public required long Timestamp { get; init; }

    /// <summary>
    /// Signature
    /// </summary>
    public required string Signature { get; init; }

    /// <summary>
    /// <list type="bullet">
    ///   <item><description><c>TRUE</c> - For isolated margin</description></item>
    ///   <item><description><c>FALSE</c> - Default, not for isolated margin</description></item>
    /// </list>
    /// </summary>
    public IsIsolated? IsIsolated { get; init; }

    /// <summary>
    /// Quote quantity
    /// </summary>
    public double? QuoteOrderQty { get; init; }

    /// <summary>
    /// Order price
    /// </summary>
    public double? Price { get; init; }

    /// <summary>
    /// Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.
    /// </summary>
    public double? StopPrice { get; init; }

    /// <summary>
    /// Used to uniquely identify this cancel. Automatically generated by default
    /// </summary>
    public string? NewClientOrderId { get; init; }

    /// <summary>
    /// Used with LIMIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT to create an iceberg order.
    /// </summary>
    public double? IcebergQty { get; init; }

    /// <summary>
    /// Set the response JSON.
    /// </summary>
    public NewOrderRespType? NewOrderRespType { get; init; }

    /// <summary>
    /// Default <c>NO_SIDE_EFFECT</c>
    /// </summary>
    public SideEffectType? SideEffectType { get; init; }

    /// <summary>
    /// Order time in force
    /// </summary>
    public TimeInForce? TimeInForce { get; init; }

    /// <summary>
    /// The allowed enums is dependent on what is configured on the symbol. The possible supported values are EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH, NONE.
    /// </summary>
    public SelfTradePreventionMode? SelfTradePreventionMode { get; init; }

    /// <summary>
    /// The value cannot be greater than 60000
    /// </summary>
    public long? RecvWindow { get; init; }
}
