using Binance.Models.Enums;

namespace Binance.Requests.TradeApi;

/// <summary>
/// The inputs of the CancelAnExistingOrderAndSendANewOrderTrade operation.
/// </summary>
public sealed record CancelAnExistingOrderAndSendANewOrderTradeRequest
{
    /// <summary>
    /// Trading symbol, e.g. BNBUSDT
    /// </summary>
    public required string Symbol { get; init; }

    public required Side Side { get; init; }

    /// <summary>
    /// Order type
    /// </summary>
    public required Type1 Type { get; init; }

    /// <summary>
    /// <list type="bullet">
    ///   <item><description><c>STOP_ON_FAILURE</c> If the cancel request fails, the new order placement will not be attempted.</description></item>
    ///   <item><description><c>ALLOW_FAILURES</c> If new order placement will be attempted even if cancel request fails.</description></item>
    /// </list>
    /// </summary>
    public required string CancelReplaceMode { get; init; }

    /// <summary>
    /// UTC timestamp in ms
    /// </summary>
    public required long Timestamp { get; init; }

    /// <summary>
    /// Signature
    /// </summary>
    public required string Signature { get; init; }

    public CancelRestrictions? CancelRestrictions { get; init; }

    /// <summary>
    /// Order time in force
    /// </summary>
    public TimeInForce? TimeInForce { get; init; }

    /// <summary>
    /// Order quantity
    /// </summary>
    public double? Quantity { get; init; }

    /// <summary>
    /// Quote quantity
    /// </summary>
    public double? QuoteOrderQty { get; init; }

    /// <summary>
    /// Order price
    /// </summary>
    public double? Price { get; init; }

    /// <summary>
    /// Used to uniquely identify this cancel. Automatically generated by default
    /// </summary>
    public string? CancelNewClientOrderId { get; init; }

    /// <summary>
    /// Either the cancelOrigClientOrderId or cancelOrderId must be provided. If both are provided, cancelOrderId takes precedence.
    /// </summary>
    public string? CancelOrigClientOrderId { get; init; }

    /// <summary>
    /// Either the cancelOrigClientOrderId or cancelOrderId must be provided. If both are provided, cancelOrderId takes precedence.
    /// </summary>
    public long? CancelOrderId { get; init; }

    /// <summary>
    /// Used to uniquely identify this cancel. Automatically generated by default
    /// </summary>
    public string? NewClientOrderId { get; init; }

    public long? StrategyId { get; init; }

    /// <summary>
    /// The value cannot be less than 1000000.
    /// </summary>
    public long? StrategyType { get; init; }

    /// <summary>
    /// Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.
    /// </summary>
    public double? StopPrice { get; init; }

    /// <summary>
    /// Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.
    /// </summary>
    public double? TrailingDelta { get; init; }

    /// <summary>
    /// Used with LIMIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT to create an iceberg order.
    /// </summary>
    public double? IcebergQty { get; init; }

    /// <summary>
    /// Set the response JSON. MARKET and LIMIT order types default to FULL, all other orders default to ACK.
    /// </summary>
    public NewOrderRespType? NewOrderRespType { get; init; }

    /// <summary>
    /// The allowed enums is dependent on what is configured on the symbol. The possible supported values are EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH, NONE.
    /// </summary>
    public SelfTradePreventionMode? SelfTradePreventionMode { get; init; }

    /// <summary>
    /// The value cannot be greater than 60000
    /// </summary>
    public long? RecvWindow { get; init; }
}
