using Binance.Models.Enums;

namespace Binance.Requests.TradeApi;

/// <summary>
/// The inputs of the CancelOrderTrade operation.
/// </summary>
public sealed record CancelOrderTradeRequest
{
    /// <summary>
    /// Trading symbol, e.g. BNBUSDT
    /// </summary>
    public required string Symbol { get; init; }

    /// <summary>
    /// UTC timestamp in ms
    /// </summary>
    public required long Timestamp { get; init; }

    /// <summary>
    /// Signature
    /// </summary>
    public required string Signature { get; init; }

    /// <summary>
    /// Order id
    /// </summary>
    public long? OrderId { get; init; }

    /// <summary>
    /// Order id from client
    /// </summary>
    public string? OrigClientOrderId { get; init; }

    /// <summary>
    /// Used to uniquely identify this cancel. Automatically generated by default
    /// </summary>
    public string? NewClientOrderId { get; init; }

    public CancelRestrictions? CancelRestrictions { get; init; }

    /// <summary>
    /// The value cannot be greater than 60000
    /// </summary>
    public long? RecvWindow { get; init; }
}
