namespace Binance.Requests.TradeApi;

/// <summary>
/// The inputs of the CancelOcoTrade operation.
/// </summary>
public sealed record CancelOcoTradeRequest
{
    /// <summary>
    /// Trading symbol, e.g. BNBUSDT
    /// </summary>
    public required string Symbol { get; init; }

    /// <summary>
    /// UTC timestamp in ms
    /// </summary>
    public required long Timestamp { get; init; }

    /// <summary>
    /// Signature
    /// </summary>
    public required string Signature { get; init; }

    /// <summary>
    /// Order list id
    /// </summary>
    public long? OrderListId { get; init; }

    /// <summary>
    /// A unique Id for the entire orderList
    /// </summary>
    public string? ListClientOrderId { get; init; }

    /// <summary>
    /// Used to uniquely identify this cancel. Automatically generated by default
    /// </summary>
    public string? NewClientOrderId { get; init; }

    /// <summary>
    /// The value cannot be greater than 60000
    /// </summary>
    public long? RecvWindow { get; init; }
}
